spring.application.name=register-service
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.enabled=true

spring.cloud.compatibility-verifier.enabled=false
