spring.application.name=api-gateway

server.port=8083

# EUREKA CLIENT
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ========================
# GATEWAY ROUTES
# ========================

# ---- ORDER SERVICE ----
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://order-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/orders/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# ---- INVENTORY SERVICE ----
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/products/**