spring.application.name=inventory-service
server.port=8081
#spring.data.mongodb.uri=mongodb://root:password@localhost:27017/inventoryservice
spring.data.mongodb.uri=mongodb://localhost:27017/inventoryservice
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.

# Cambiar la ruta base de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Cambiar la ruta del documento OpenAPI (JSON/YAML)
springdoc.api-docs.path=/api-docs

# Habilitar/deshabilitar Swagger UI
springdoc.swagger-ui.enabled=true

spring.rabbitmq.host= localhost
spring.rabbitmq.port= 5672
spring.rabbitmq.username= guest
spring.rabbitmq.password= guest
